### ISSUE TITLE
Complete the Sign in feature of the Automated Onboarding system

### ISSUE THREAD

**Issue by ModalHydra** [UTDallasEPICS/Warren-Automated-Onboard#20] opened 2022-09-16 00:29 UTC
The completion of the feature requires a database with at least an employee table to hold the email/username and password of the employee signing in. Additionally, the current sign-in page will need to be modified to request verification from the database on the email/username and password and send the user to the home page upon the verification being correct. Finally this step requires that the web application and the database be connected for the verification to take place.

This feature can be tested by manually inserting an email/username and password into the created employee table and trying to sign in as that employee.

**Comment by MStolen** [comment] 2023-09-21 04:50
Duplicate of #32

**Closed as not planned by MStolen** 2023-09-21 04:50 UTC
Labels: duplicate
